### ISSUE TITLE
Ver si wollok-ts puede guardar el texto de los bloques.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok-sanity-tests#4]
```
test "Assert throws exception failing" {
	
	var a = 0
	assert.throwsExceptionLike(
		// TODO NicoS: es posible hacer que wollok-ts nos dé el código acá?
		new AssertionException(message = "Block { a + 1 } should have failed"),
		{ assert.throwsException({ a + 1 }) }
	)

}
```

**Comment by nscarcella** [comment]
Sí, se puede.

Ya hay [un branch](https://github.com/uqbar-project/wollok-ts/tree/closures-tostring) creado que hace esto.

De todos modos, propongo crear un nuevo test para el toString del bloque y acá chequear solamente que se lanzó una excepción como estamos haciendo en los otros lugares.

Si querés @npasserini ya lo tengo hecho, sólo tengo que pushear.

**Comment by npasserini** [comment]
Dale, para adelante, lo que vos digas.

**Comment by nscarcella** [comment]
Bueno, mergié el branch con el sanity test nuevo y actualicé el master de wollok-ts con la implementación que se guarda el código.
@npasserini si querés cambiá este test para solo chequear que lanza, ahora que lo otro ya está cubierto.
